/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import connection.ConnectNotUse;
import java.awt.BorderLayout;

import java.awt.Color;
import java.awt.Font;
import javax.swing.SwingConstants;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import model.DishesButton;

/**
 *
 * @author jiang
 */
public class NhanVienGUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public NhanVienGUI() {
        initComponents();
        themMonAn();
        showGui();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        themNV_jDialog = new javax.swing.JDialog();
        idNhanVien_jLabel = new javax.swing.JLabel();
        hoTen__jLabel = new javax.swing.JLabel();
        cccd_jLabel = new javax.swing.JLabel();
        soDienThoai_jLabel = new javax.swing.JLabel();
        gioi_Tinh_jLabel = new javax.swing.JLabel();
        eMail_jLabel = new javax.swing.JLabel();
        ngaySinh_jLabel = new javax.swing.JLabel();
        chucVu_jLabel = new javax.swing.JLabel();
        ngayVaoLam_jLabel = new javax.swing.JLabel();
        luong_jLabel = new javax.swing.JLabel();
        diaChi_jLabel = new javax.swing.JLabel();
        idNhanVien_jTextField = new javax.swing.JTextField();
        cccd_jTextField = new javax.swing.JTextField();
        hoTen_jTextField = new javax.swing.JTextField();
        gioiTinh_JComboBox = new javax.swing.JComboBox<>();
        ngaySinh_jTextField = new javax.swing.JTextField();
        chucVu_jTextField = new javax.swing.JTextField();
        ngayVaoLam_jTextField = new javax.swing.JTextField();
        luong_jTextField = new javax.swing.JTextField();
        diaChi_jTextField = new javax.swing.JTextField();
        confirm_ThemNV_Button = new javax.swing.JButton();
        cancel_themNV_jButton = new javax.swing.JButton();
        email_JTextField = new javax.swing.JTextField();
        soDienThoai_jFormattedTextField = new javax.swing.JFormattedTextField();
        ngaySinh_dateChooser = new com.raven.datechooser.DateChooser();
        ngayVaoLam_dateChooser = new com.raven.datechooser.DateChooser();
        confirm_themNV_jOptionPane = new javax.swing.JOptionPane();
        themMonAn_jDialog = new javax.swing.JDialog();
        themAnhMonAnTuFile_jButton = new javax.swing.JButton();
        themTenMonAn_jTextField = new javax.swing.JTextField();
        themTenMon_jLabel = new javax.swing.JLabel();
        confirmThemMonAn_jButton = new javax.swing.JButton();
        themLoaiMonAn_jTextField = new javax.swing.JTextField();
        themLoaiMonAn_jLabel = new javax.swing.JLabel();
        themAnhMonAn_jLabel = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        themMonAn_jFileChooser = new javax.swing.JFileChooser();
        confirmThemMonAn_jOptionPane = new javax.swing.JOptionPane();
        xoa_suaMonAn_jDialog = new javax.swing.JDialog();
        suaTenMonAn_jLabel = new javax.swing.JLabel();
        suaTenMonAn_jTextField = new javax.swing.JTextField();
        themLoaiMonAn_jLabel1 = new javax.swing.JLabel();
        suaLoaiMonAn_jTextField = new javax.swing.JTextField();
        suaAnhMonAn_jLabel1 = new javax.swing.JLabel();
        suaAnhMonAnTuFile_jButton = new javax.swing.JButton();
        confirm_SuaMonAn_jButton1 = new javax.swing.JButton();
        xoaMonAn_jButton = new javax.swing.JButton();
        cancle_XoaSuaMonAn_jButton = new javax.swing.JButton();
        quanLyKho_jPanel = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        quanLyHoaDon_jPanel = new javax.swing.JPanel();
        quanLyKhachHang_jPanel = new javax.swing.JPanel();
        quanLyNhanVien_jPanel = new javax.swing.JPanel();
        searchNhanVienTheo_jComboBox = new javax.swing.JComboBox<>();
        themNV_jButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showNhanVien_jTable = new javax.swing.JTable();
        searchNhanVien_jPanel = new javax.swing.JPanel();
        searchNhanVien_jTextField = new javax.swing.JTextField();
        searchNhanVien_jButton = new javax.swing.JButton();
        quanLyThucDon_jPanel = new javax.swing.JPanel();
        searchMonAnTheo_jComboBox = new javax.swing.JComboBox<>();
        themMonAn_jButton = new javax.swing.JButton();
        searchMonAn_jPanel = new javax.swing.JPanel();
        searchMonAn_jTextField = new javax.swing.JTextField();
        searchMonAn_jButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel21 = new javax.swing.JPanel();
        thanhBen_JPanel = new keeptoo.KGradientPanel();
        nhanVien_jButton = new javax.swing.JButton();
        khachHang_jButton = new javax.swing.JButton();
        hoaDon_jButton = new javax.swing.JButton();
        thucDon_jButton = new javax.swing.JButton();
        kho_jButton = new javax.swing.JButton();

        themNV_jDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        themNV_jDialog.setMinimumSize(new java.awt.Dimension(600, 450));
        themNV_jDialog.setModal(true);
        themNV_jDialog.setResizable(false);
        java.awt.GridBagLayout themNV_jDialogLayout = new java.awt.GridBagLayout();
        themNV_jDialogLayout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        themNV_jDialogLayout.rowHeights = new int[] {0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0};
        themNV_jDialog.getContentPane().setLayout(themNV_jDialogLayout);

        idNhanVien_jLabel.setText("ID Nhân viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(idNhanVien_jLabel, gridBagConstraints);

        hoTen__jLabel.setText("CMND/CCCD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 54;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(hoTen__jLabel, gridBagConstraints);

        cccd_jLabel.setText("Họ tên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(cccd_jLabel, gridBagConstraints);

        soDienThoai_jLabel.setText("Số điện thoại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(soDienThoai_jLabel, gridBagConstraints);

        gioi_Tinh_jLabel.setText("Giới tính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(gioi_Tinh_jLabel, gridBagConstraints);

        eMail_jLabel.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 54;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(eMail_jLabel, gridBagConstraints);

        ngaySinh_jLabel.setText("Ngày sinh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(ngaySinh_jLabel, gridBagConstraints);

        chucVu_jLabel.setText("Chức vụ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 54;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(chucVu_jLabel, gridBagConstraints);

        ngayVaoLam_jLabel.setText("Ngày vào làm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(ngayVaoLam_jLabel, gridBagConstraints);

        luong_jLabel.setText("Lương");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(luong_jLabel, gridBagConstraints);

        diaChi_jLabel.setText("Địa chỉ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(diaChi_jLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(idNhanVien_jTextField, gridBagConstraints);

        cccd_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cccd_jTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 54;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(cccd_jTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(hoTen_jTextField, gridBagConstraints);

        gioiTinh_JComboBox.setMaximumRowCount(2);
        gioiTinh_JComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        gioiTinh_JComboBox.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(gioiTinh_JComboBox, gridBagConstraints);

        ngaySinh_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngaySinh_jTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(ngaySinh_jTextField, gridBagConstraints);

        chucVu_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chucVu_jTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 54;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(chucVu_jTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(ngayVaoLam_jTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(luong_jTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 45;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(diaChi_jTextField, gridBagConstraints);

        confirm_ThemNV_Button.setText("XÁC NHẬN");
        confirm_ThemNV_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_ThemNV_ButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 54;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(confirm_ThemNV_Button, gridBagConstraints);

        cancel_themNV_jButton.setText("HỦY");
        cancel_themNV_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_themNV_jButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 66;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(cancel_themNV_jButton, gridBagConstraints);

        email_JTextField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e) {
                if (!email_JTextField.getText().endsWith("@gmail.com")) {
                    email_JTextField.setText(email_JTextField.getText() + "@gmail.com");
                }
            }
        });
        email_JTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                email_JTextFieldFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 54;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(email_JTextField, gridBagConstraints);

        soDienThoai_jFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("'0'"))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(soDienThoai_jFormattedTextField, gridBagConstraints);

        ngaySinh_dateChooser.setForeground(new java.awt.Color(167, 223, 255));
        ngaySinh_dateChooser.setTextRefernce(ngaySinh_jTextField);

        ngayVaoLam_dateChooser.setForeground(new java.awt.Color(255, 184, 183));
        ngayVaoLam_dateChooser.setTextRefernce(ngayVaoLam_jTextField);

        confirm_themNV_jOptionPane.setOptionType(0);

        themAnhMonAnTuFile_jButton.setText("Choose File");
        themAnhMonAnTuFile_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themAnhMonAnTuFile_jButtonActionPerformed(evt);
            }
        });

        themTenMonAn_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themTenMonAn_jTextFieldActionPerformed(evt);
            }
        });

        themTenMon_jLabel.setText("Tên món");

        confirmThemMonAn_jButton.setText("Xác Nhận");
        confirmThemMonAn_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmThemMonAn_jButtonActionPerformed(evt);
            }
        });

        themLoaiMonAn_jLabel.setText("Loại món ăn");

        themAnhMonAn_jLabel.setText("Chọn ảnh món ăn");

        jButton9.setText("Hủy");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout themMonAn_jDialogLayout = new javax.swing.GroupLayout(themMonAn_jDialog.getContentPane());
        themMonAn_jDialog.getContentPane().setLayout(themMonAn_jDialogLayout);
        themMonAn_jDialogLayout.setHorizontalGroup(
            themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themMonAn_jDialogLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(themMonAn_jDialogLayout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmThemMonAn_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(themAnhMonAnTuFile_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(themLoaiMonAn_jTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                        .addComponent(themTenMon_jLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(themLoaiMonAn_jLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(themAnhMonAn_jLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(themTenMonAn_jTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        themMonAn_jDialogLayout.setVerticalGroup(
            themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themMonAn_jDialogLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(themTenMon_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themTenMonAn_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(themLoaiMonAn_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themLoaiMonAn_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(themAnhMonAn_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themAnhMonAnTuFile_jButton)
                .addGap(34, 34, 34)
                .addGroup(themMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmThemMonAn_jButton)
                    .addComponent(jButton9))
                .addGap(38, 38, 38))
        );

        themMonAn_jFileChooser.setCurrentDirectory(new java.io.File("D:\\Java_Code\\DO_AN_2\\src\\image"));

        suaTenMonAn_jLabel.setText("Tên món");

        suaTenMonAn_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaTenMonAn_jTextFieldActionPerformed(evt);
            }
        });

        themLoaiMonAn_jLabel1.setText("Loại món ăn");

        suaAnhMonAn_jLabel1.setText("Chọn ảnh món ăn");

        suaAnhMonAnTuFile_jButton.setText("Choose File");
        suaAnhMonAnTuFile_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaAnhMonAnTuFile_jButtonActionPerformed(evt);
            }
        });

        confirm_SuaMonAn_jButton1.setText("Sửa");
        confirm_SuaMonAn_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_SuaMonAn_jButton1ActionPerformed(evt);
            }
        });

        xoaMonAn_jButton.setText("Xóa");

        cancle_XoaSuaMonAn_jButton.setText("Hủy");

        javax.swing.GroupLayout xoa_suaMonAn_jDialogLayout = new javax.swing.GroupLayout(xoa_suaMonAn_jDialog.getContentPane());
        xoa_suaMonAn_jDialog.getContentPane().setLayout(xoa_suaMonAn_jDialogLayout);
        xoa_suaMonAn_jDialogLayout.setHorizontalGroup(
            xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xoa_suaMonAn_jDialogLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(xoa_suaMonAn_jDialogLayout.createSequentialGroup()
                        .addGroup(xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(xoa_suaMonAn_jDialogLayout.createSequentialGroup()
                                .addComponent(suaAnhMonAnTuFile_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 102, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xoa_suaMonAn_jDialogLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cancle_XoaSuaMonAn_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(xoaMonAn_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addComponent(confirm_SuaMonAn_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(suaLoaiMonAn_jTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                        .addComponent(suaTenMonAn_jLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(themLoaiMonAn_jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(suaAnhMonAn_jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(suaTenMonAn_jTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        xoa_suaMonAn_jDialogLayout.setVerticalGroup(
            xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xoa_suaMonAn_jDialogLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(suaTenMonAn_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suaTenMonAn_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(themLoaiMonAn_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suaLoaiMonAn_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(suaAnhMonAn_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suaAnhMonAnTuFile_jButton)
                .addGap(33, 33, 33)
                .addGroup(xoa_suaMonAn_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm_SuaMonAn_jButton1)
                    .addComponent(xoaMonAn_jButton)
                    .addComponent(cancle_XoaSuaMonAn_jButton))
                .addGap(39, 39, 39))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("quanLyNhanVien_jFrame");
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel1Layout.rowHeights = new int[] {0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0};
        quanLyKho_jPanel.setLayout(jPanel1Layout);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 54;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 31;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        quanLyKho_jPanel.add(jComboBox1, gridBagConstraints);

        jButton3.setText("jButton3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 110;
        gridBagConstraints.gridy = 184;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        quanLyKho_jPanel.add(jButton3, gridBagConstraints);

        jButton4.setText("jButton4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 94;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        quanLyKho_jPanel.add(jButton4, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MÃ NGUYÊN LIỆU", "TÊN NGUYÊN LIỆU", "ĐƠN GIÁ", "ĐƠN VỊ", "TỔNG SỐ LƯỢNG ", "THAO TÁC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.setMinimumSize(new java.awt.Dimension(90, 600));
        jTable1.setPreferredSize(new java.awt.Dimension(550, 420));
        jTable1.setShowGrid(true);
        jScrollPane2.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 129;
        gridBagConstraints.gridheight = 177;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        quanLyKho_jPanel.add(jScrollPane2, gridBagConstraints);

        jButton5.setText("jButton5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 110;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        quanLyKho_jPanel.add(jButton5, gridBagConstraints);

        getContentPane().add(quanLyKho_jPanel, java.awt.BorderLayout.CENTER);
        getContentPane().add(quanLyHoaDon_jPanel, java.awt.BorderLayout.CENTER);
        getContentPane().add(quanLyKhachHang_jPanel, java.awt.BorderLayout.CENTER);

        quanLyNhanVien_jPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(250, 300, 250, 300));
        quanLyNhanVien_jPanel.setPreferredSize(new java.awt.Dimension(900, 600));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel3Layout.rowHeights = new int[] {0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0};
        quanLyNhanVien_jPanel.setLayout(jPanel3Layout);

        searchNhanVienTheo_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo tên", "Theo mã nhân viên" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 52;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 43;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        quanLyNhanVien_jPanel.add(searchNhanVienTheo_jComboBox, gridBagConstraints);

        javax.swing.ImageIcon themNVIcon = new javax.swing.ImageIcon(getClass().getResource("/image/add_empl.png"));
        java.awt.Image themNVImage = themNVIcon.getImage().getScaledInstance(20,20, java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon scaledThemNVIcon = new javax.swing.ImageIcon(themNVImage);
        themNV_jButton.setIcon(scaledThemNVIcon);
        themNV_jButton.setOpaque(false);
        themNV_jButton.setText("THÊM MỚI");
        themNV_jButton.setToolTipText("Thêm nhân viên mới");
        themNV_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themNV_jButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 120;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 27;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        quanLyNhanVien_jPanel.add(themNV_jButton, gridBagConstraints);

        showNhanVien_jTable.setAutoCreateRowSorter(true);
        showNhanVien_jTable.setShowVerticalLines(true);
        showNhanVien_jTable.setShowHorizontalLines(true);
        showNhanVien_jTable.getTableHeader().setUpdateTableInRealTime(true);
        showNhanVien_jTable.getTableHeader().setBackground(new Color(167,222,254));

        showNhanVien_jTable.getTableHeader().setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        showNhanVien_jTable.getTableHeader().setFont(showNhanVien_jTable.getTableHeader().getFont().deriveFont(Font.BOLD));
        showNhanVien_jTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        showNhanVien_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MÃ NHÂN VIÊN", "HỌ TÊN", "GIỚI TÍNH", "CHỨC VỤ", "QUÊ QUÁN", "LƯƠNG", "CHỨC NĂNG"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        showNhanVien_jTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        showNhanVien_jTable.setGridColor(new java.awt.Color(204, 204, 204));
        showNhanVien_jTable.setShowGrid(true);
        jScrollPane1.setViewportView(showNhanVien_jTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 147;
        gridBagConstraints.gridheight = 325;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        quanLyNhanVien_jPanel.add(jScrollPane1, gridBagConstraints);

        searchNhanVien_jPanel.setLayout(new javax.swing.BoxLayout(searchNhanVien_jPanel, javax.swing.BoxLayout.X_AXIS));

        searchNhanVien_jTextField.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        searchNhanVien_jTextField.setText("Search...");
        searchNhanVien_jTextField.setName(""); // NOI18N
        searchNhanVien_jTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchNhanVien_jTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchNhanVien_jTextFieldFocusLost(evt);
            }
        });
        searchNhanVien_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNhanVien_jTextFieldActionPerformed(evt);
            }
        });
        searchNhanVien_jPanel.add(searchNhanVien_jTextField);

        javax.swing.ImageIcon searchNhanVienIcon = new javax.swing.ImageIcon(getClass().getResource("/image/search.png"));
        java.awt.Image searchNhanVienImage = searchNhanVienIcon.getImage().getScaledInstance(20,20, java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon scaledSearchNhanVienIcon = new javax.swing.ImageIcon(searchNhanVienImage);
        searchNhanVien_jButton.setIcon(scaledSearchNhanVienIcon);
        searchNhanVien_jButton.setToolTipText("");
        searchNhanVien_jButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchNhanVien_jPanel.add(searchNhanVien_jButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 47;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        quanLyNhanVien_jPanel.add(searchNhanVien_jPanel, gridBagConstraints);

        getContentPane().add(quanLyNhanVien_jPanel, java.awt.BorderLayout.CENTER);

        quanLyThucDon_jPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(250, 300, 250, 300));
        quanLyThucDon_jPanel.setPreferredSize(new java.awt.Dimension(900, 600));
        quanLyThucDon_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchMonAnTheo_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo tên món ăn", "Theo loại món ăn" }));
        quanLyThucDon_jPanel.add(searchMonAnTheo_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 190, 30));

        javax.swing.ImageIcon themMonAnIcon = new javax.swing.ImageIcon(getClass().getResource("/image/add_dishes.png"));
        java.awt.Image themMonAnImage = themMonAnIcon.getImage().getScaledInstance(20,20, java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon scaledThemMonAnIcon = new javax.swing.ImageIcon(themMonAnImage);
        themMonAn_jButton.setIcon(scaledThemMonAnIcon);
        themMonAn_jButton.setText("THÊM MÓN");
        themMonAn_jButton.setToolTipText("Thêm món ăn mới");
        themMonAn_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themMonAn_jButtonActionPerformed(evt);
            }
        });
        quanLyThucDon_jPanel.add(themMonAn_jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 150, 30));

        searchMonAn_jPanel.setLayout(new javax.swing.BoxLayout(searchMonAn_jPanel, javax.swing.BoxLayout.X_AXIS));

        searchMonAn_jTextField.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        searchMonAn_jTextField.setText("Search...");
        searchMonAn_jTextField.setName(""); // NOI18N
        searchMonAn_jTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchMonAn_jTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchMonAn_jTextFieldFocusLost(evt);
            }
        });
        searchMonAn_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMonAn_jTextFieldActionPerformed(evt);
            }
        });
        searchMonAn_jPanel.add(searchMonAn_jTextField);

        javax.swing.ImageIcon searchMonAnIcon = new javax.swing.ImageIcon(getClass().getResource("/image/search.png"));
        java.awt.Image searchMonAnImage = searchMonAnIcon.getImage().getScaledInstance(20,20, java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon scaledSearchMonAnIcon = new javax.swing.ImageIcon(searchMonAnImage);
        searchMonAn_jButton1.setIcon(scaledSearchMonAnIcon);
        searchMonAn_jButton1.setToolTipText("");
        searchMonAn_jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchMonAn_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMonAn_jButton1ActionPerformed(evt);
            }
        });
        searchMonAn_jPanel.add(searchMonAn_jButton1);

        quanLyThucDon_jPanel.add(searchMonAn_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 285, 30));

        jButton1.setText("jButton1");
        quanLyThucDon_jPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jButton2.setText("jButton2");
        quanLyThucDon_jPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jButton6.setText("jButton6");
        quanLyThucDon_jPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setPreferredSize(new java.awt.Dimension(400, 612));

        jPanel1.setLayout(new java.awt.GridLayout(0, 3));
        jScrollPane3.setViewportView(jPanel1);

        jTabbedPane1.addTab("SHASHIMI", jScrollPane3);

        jScrollPane4.setViewportView(jPanel20);

        jTabbedPane1.addTab("SALAD", jScrollPane4);

        jScrollPane5.setViewportView(jPanel12);

        jTabbedPane1.addTab("UDON", jScrollPane5);

        jScrollPane6.setViewportView(jPanel21);

        jTabbedPane1.addTab("TEMPURA", jScrollPane6);

        quanLyThucDon_jPanel.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 730, 440));

        getContentPane().add(quanLyThucDon_jPanel, java.awt.BorderLayout.CENTER);

        thanhBen_JPanel.setkEndColor(new java.awt.Color(255, 184, 183));
        thanhBen_JPanel.setkGradientFocus(200);
        thanhBen_JPanel.setkStartColor(new java.awt.Color(167, 223, 255));
        thanhBen_JPanel.setLayout(new java.awt.GridLayout(6, 1));

        nhanVien_jButton.setVerticalTextPosition(SwingConstants.BOTTOM);
        nhanVien_jButton.setHorizontalTextPosition(SwingConstants.CENTER);
        nhanVien_jButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        javax.swing.ImageIcon nhanVienIcon = new javax.swing.ImageIcon(getClass().getResource("/image/employee.png"));
        java.awt.Image nhanVienImage = nhanVienIcon.getImage().getScaledInstance(50,50, java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon scaledNhanVienIcon = new javax.swing.ImageIcon(nhanVienImage);
        nhanVien_jButton.setIcon(scaledNhanVienIcon);
        nhanVien_jButton.setText("NHÂN VIÊN");
        nhanVien_jButton.setToolTipText("Hiển thị trang quản lý nhân viên");
        nhanVien_jButton.setOpaque(true);
        nhanVien_jButton.setOpaque(false);
        nhanVien_jButton.setContentAreaFilled(false);
        nhanVien_jButton.setBorderPainted(false);
        nhanVien_jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nhanVien_jButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nhanVien_jButtonMouseExited(evt);
            }
        });
        nhanVien_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanVien_jButtonActionPerformed(evt);
            }
        });
        thanhBen_JPanel.add(nhanVien_jButton);

        khachHang_jButton.setOpaque(false);
        khachHang_jButton.setContentAreaFilled(false);
        khachHang_jButton.setBorderPainted(false);
        khachHang_jButton.setVerticalTextPosition(SwingConstants.BOTTOM);
        khachHang_jButton.setHorizontalTextPosition(SwingConstants.CENTER);
        javax.swing.ImageIcon khachHangIcon = new javax.swing.ImageIcon(getClass().getResource("/image/guest.png"));
        java.awt.Image khachHangImage = khachHangIcon.getImage().getScaledInstance(50,50,java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon scaledKhachHangIcon = new javax.swing.ImageIcon(khachHangImage);
        khachHang_jButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        khachHang_jButton.setIcon(scaledKhachHangIcon);
        khachHang_jButton.setText("KHÁCH HÀNG");
        khachHang_jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                khachHang_jButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                khachHang_jButtonMouseExited(evt);
            }
        });
        khachHang_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khachHang_jButtonActionPerformed(evt);
            }
        });
        thanhBen_JPanel.add(khachHang_jButton);

        hoaDon_jButton.setOpaque(false);
        hoaDon_jButton.setContentAreaFilled(false);
        hoaDon_jButton.setBorderPainted(false);
        hoaDon_jButton.setVerticalTextPosition(SwingConstants.BOTTOM);
        hoaDon_jButton.setHorizontalTextPosition(SwingConstants.CENTER);
        ImageIcon hoaDonIcon = new javax.swing.ImageIcon(getClass().getResource("/image/bill.png"));
        Image hoaDonImage = hoaDonIcon.getImage().getScaledInstance(50,50,java.awt.Image.SCALE_SMOOTH);
        ImageIcon scaledHoaDonIcon = new ImageIcon(hoaDonImage);
        hoaDon_jButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hoaDon_jButton.setIcon(scaledHoaDonIcon);
        hoaDon_jButton.setText("HÓA ĐƠN");
        hoaDon_jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoaDon_jButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoaDon_jButtonMouseExited(evt);
            }
        });
        hoaDon_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoaDon_jButtonActionPerformed(evt);
            }
        });
        thanhBen_JPanel.add(hoaDon_jButton);

        thucDon_jButton.setOpaque(false);
        thucDon_jButton.setContentAreaFilled(false);
        thucDon_jButton.setBorderPainted(false);
        thucDon_jButton.setVerticalTextPosition(SwingConstants.BOTTOM);
        thucDon_jButton.setHorizontalTextPosition(SwingConstants.CENTER);
        ImageIcon thucDonIcon = new ImageIcon(getClass().getResource("/image/menu.png"));
        Image thucImage = thucDonIcon.getImage().getScaledInstance(50,50,java.awt.Image.SCALE_SMOOTH);
        ImageIcon scaledThucDonIcon = new ImageIcon(thucImage);
        thucDon_jButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        thucDon_jButton.setIcon(scaledThucDonIcon);
        thucDon_jButton.setText("THỰC ĐƠN");
        thucDon_jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                thucDon_jButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                thucDon_jButtonMouseExited(evt);
            }
        });
        thucDon_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thucDon_jButtonActionPerformed(evt);
            }
        });
        thanhBen_JPanel.add(thucDon_jButton);

        kho_jButton.setOpaque(false);
        kho_jButton.setContentAreaFilled(false);
        kho_jButton.setBorderPainted(false);
        kho_jButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kho_jButton.setVerticalTextPosition(SwingConstants.BOTTOM);
        kho_jButton.setHorizontalTextPosition(SwingConstants.CENTER);
        ImageIcon khoIcon = new javax.swing.ImageIcon(getClass().getResource("/image/cardboard.png"));
        Image khoImage = khoIcon.getImage().getScaledInstance(50,50,java.awt.Image.SCALE_SMOOTH);
        ImageIcon scaledKhoIcon = new ImageIcon(khoImage);
        kho_jButton.setIcon(scaledKhoIcon);
        kho_jButton.setText("KHO");
        kho_jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kho_jButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kho_jButtonMouseExited(evt);
            }
        });
        kho_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kho_jButtonActionPerformed(evt);
            }
        });
        thanhBen_JPanel.add(kho_jButton);

        getContentPane().add(thanhBen_JPanel, java.awt.BorderLayout.LINE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showGui()
    {
        

        /* Create and display the form */
        this.setVisible(true);
    }
    private void themMonAn() {
            ArrayList<DishesButton> listDishesButtons = new ArrayList<>();
        try {
            ConnectNotUse conn = new ConnectNotUse();
            Connection con = conn.LinkConnection("jdbc:oracle:thin:@//localhost:1521/orcl", "MANAGER_RES", "1");
            Statement st = con.createStatement();
            String sqlQuery = "select * from MONAN";
            ResultSet resultSet = st.executeQuery(sqlQuery);
            while (resultSet.next()) {
                String link_image = resultSet.getString("LINK_IMAGE");
                String tenMon = resultSet.getString("TENMON");
                System.out.println(link_image);
                System.out.println(tenMon);
//                DishesButton testButton = new DishesButton(link_image, tenMon);
//                listDishesButtons.add(testButton);
//                jPanel1.add(testButton);
            }
                     
           DishesButton b = listDishesButtons.get(1);
           b.setText("copyshushi");
           jPanel1.add(b);
            
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    private void cancel_themNV_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_themNV_jButtonActionPerformed
        // TODO add your handling code here:
        themNV_jDialog.setVisible(false);
        idNhanVien_jTextField.setText("");
        hoTen_jTextField.setText("");
        cccd_jTextField.setText("");
        soDienThoai_jFormattedTextField.setText("");
        gioiTinh_JComboBox.setSelectedItem("Nam");
        email_JTextField.setText("");
        chucVu_jTextField.setText("");
        luong_jTextField.setText("");
        diaChi_jTextField.setText("");
    }//GEN-LAST:event_cancel_themNV_jButtonActionPerformed

    private void cccd_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cccd_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cccd_jTextFieldActionPerformed

    private void chucVu_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chucVu_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chucVu_jTextFieldActionPerformed

    private void khachHang_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khachHang_jButtonActionPerformed
        // TODO add your handling code here:
        if (quanLyNhanVien_jPanel.isDisplayable()) {
            quanLyNhanVien_jPanel.setVisible(false);
        }
        if (quanLyHoaDon_jPanel.isDisplayable()) {
            quanLyHoaDon_jPanel.setVisible(false);
        }
        if (quanLyThucDon_jPanel.isDisplayable()) {
            quanLyThucDon_jPanel.setVisible(false);
        }
        if (quanLyKho_jPanel.isDisplayable()) {
            quanLyKho_jPanel.setVisible(false);
        }
        quanLyKhachHang_jPanel.setVisible(true);
        add(quanLyKhachHang_jPanel, BorderLayout.CENTER);
    }//GEN-LAST:event_khachHang_jButtonActionPerformed

    private void nhanVien_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanVien_jButtonActionPerformed
        // TODO add your handling code here:
        if (quanLyKhachHang_jPanel.isDisplayable()) {
            quanLyKhachHang_jPanel.setVisible(false);
        }
        if (quanLyHoaDon_jPanel.isDisplayable()) {
            quanLyHoaDon_jPanel.setVisible(false);
        }
        if (quanLyThucDon_jPanel.isDisplayable()) {
            quanLyThucDon_jPanel.setVisible(false);
        }
        if (quanLyKho_jPanel.isDisplayable()) {
            quanLyKho_jPanel.setVisible(false);
        }
        quanLyNhanVien_jPanel.setVisible(true);
        add(quanLyNhanVien_jPanel, BorderLayout.CENTER);
    }//GEN-LAST:event_nhanVien_jButtonActionPerformed

    private void confirm_ThemNV_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_ThemNV_ButtonActionPerformed
        themNV_jDialog.setVisible(false);
        idNhanVien_jTextField.setText("");
        hoTen_jTextField.setText("");
        cccd_jTextField.setText("");
        soDienThoai_jFormattedTextField.setText("");
        gioiTinh_JComboBox.setSelectedItem("Nam");
        email_JTextField.setText("");
        chucVu_jTextField.setText("");
        luong_jTextField.setText("");
        diaChi_jTextField.setText("");
        confirm_themNV_jOptionPane.showMessageDialog(themNV_jDialog, "Thêm thành công nhân viên!");
    }//GEN-LAST:event_confirm_ThemNV_ButtonActionPerformed

    private void ngaySinh_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngaySinh_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngaySinh_jTextFieldActionPerformed

    private void email_JTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_JTextFieldFocusLost
        // TODO add your handling code here:
        if (!email_JTextField.getText().endsWith("@gmail.com")) {
            email_JTextField.setText(email_JTextField.getText() + "@gmail.com");
        }
    }//GEN-LAST:event_email_JTextFieldFocusLost

    private void themNV_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themNV_jButtonActionPerformed
        // TODO add your handling code here:
        themNV_jDialog.pack();
        themNV_jDialog.setLocationRelativeTo(null);
        themNV_jDialog.setVisible(true);
    }//GEN-LAST:event_themNV_jButtonActionPerformed

    private void searchNhanVien_jTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchNhanVien_jTextFieldFocusGained
        // TODO add your handling code here:
        searchNhanVien_jTextField.setText("");
        searchNhanVien_jTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

    }//GEN-LAST:event_searchNhanVien_jTextFieldFocusGained

    private void searchNhanVien_jTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchNhanVien_jTextFieldFocusLost
        // TODO add your handling code here:
        if (searchNhanVien_jTextField.getText().equals("")) {
            searchNhanVien_jTextField.setText("Search...");
            searchNhanVien_jTextField.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        }
    }//GEN-LAST:event_searchNhanVien_jTextFieldFocusLost

    private void khachHang_jButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachHang_jButtonMouseEntered
        // TODO add your handling code here:
        khachHang_jButton.setContentAreaFilled(true);
        khachHang_jButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_khachHang_jButtonMouseEntered

    private void khachHang_jButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachHang_jButtonMouseExited
        // TODO add your handling code here:
        khachHang_jButton.setContentAreaFilled(false);
    }//GEN-LAST:event_khachHang_jButtonMouseExited

    private void nhanVien_jButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanVien_jButtonMouseEntered
        // TODO add your handling code here:
        nhanVien_jButton.setContentAreaFilled(true);
        nhanVien_jButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_nhanVien_jButtonMouseEntered

    private void nhanVien_jButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanVien_jButtonMouseExited
        // TODO add your handling code here:
        nhanVien_jButton.setContentAreaFilled(false);
    }//GEN-LAST:event_nhanVien_jButtonMouseExited

    private void hoaDon_jButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoaDon_jButtonMouseEntered
        // TODO add your handling code here:
        hoaDon_jButton.setContentAreaFilled(true);
        hoaDon_jButton.setBackground(Color.getHSBColor(202, 0, (float) 0.8));
    }//GEN-LAST:event_hoaDon_jButtonMouseEntered

    private void hoaDon_jButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoaDon_jButtonMouseExited
        // TODO add your handling code here:
        hoaDon_jButton.setContentAreaFilled(false);
    }//GEN-LAST:event_hoaDon_jButtonMouseExited

    private void thucDon_jButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thucDon_jButtonMouseEntered
        // TODO add your handling code here:
        thucDon_jButton.setContentAreaFilled(true);
        thucDon_jButton.setBackground(Color.GRAY);
    }//GEN-LAST:event_thucDon_jButtonMouseEntered

    private void thucDon_jButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thucDon_jButtonMouseExited
        // TODO add your handling code here:
        thucDon_jButton.setContentAreaFilled(false);
    }//GEN-LAST:event_thucDon_jButtonMouseExited

    private void kho_jButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kho_jButtonMouseEntered
        // TODO add your handling code here:
        kho_jButton.setContentAreaFilled(true);
        kho_jButton.setBackground(Color.GRAY);
    }//GEN-LAST:event_kho_jButtonMouseEntered

    private void kho_jButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kho_jButtonMouseExited
        // TODO add your handling code here:
        kho_jButton.setContentAreaFilled(false);
    }//GEN-LAST:event_kho_jButtonMouseExited

    private void kho_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kho_jButtonActionPerformed
        // TODO add your handling code here:
        if (quanLyKhachHang_jPanel.isDisplayable()) {
            quanLyKhachHang_jPanel.setVisible(false);
        }
        if (quanLyHoaDon_jPanel.isDisplayable()) {
            quanLyHoaDon_jPanel.setVisible(false);
        }
        if (quanLyThucDon_jPanel.isDisplayable()) {
            quanLyThucDon_jPanel.setVisible(false);
        }
        if (quanLyNhanVien_jPanel.isDisplayable()) {
            quanLyNhanVien_jPanel.setVisible(false);
        }
        quanLyKho_jPanel.setVisible(true);
        add(quanLyKho_jPanel, BorderLayout.CENTER);
    }//GEN-LAST:event_kho_jButtonActionPerformed

    private void hoaDon_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoaDon_jButtonActionPerformed
        // TODO add your handling code here:
        if (quanLyKhachHang_jPanel.isDisplayable()) {
            quanLyKhachHang_jPanel.setVisible(false);
        }
        if (quanLyNhanVien_jPanel.isDisplayable()) {
            quanLyNhanVien_jPanel.setVisible(false);
        }
        if (quanLyThucDon_jPanel.isDisplayable()) {
            quanLyThucDon_jPanel.setVisible(false);
        }
        if (quanLyKho_jPanel.isDisplayable()) {
            quanLyKho_jPanel.setVisible(false);
        }
        quanLyHoaDon_jPanel.setVisible(true);
        add(quanLyHoaDon_jPanel, BorderLayout.CENTER);
    }//GEN-LAST:event_hoaDon_jButtonActionPerformed

    private void thucDon_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thucDon_jButtonActionPerformed
        // TODO add your handling code here:
        if (quanLyKhachHang_jPanel.isDisplayable()) {
            quanLyKhachHang_jPanel.setVisible(false);
        }
        if (quanLyHoaDon_jPanel.isDisplayable()) {
            quanLyHoaDon_jPanel.setVisible(false);
        }
        if (quanLyNhanVien_jPanel.isDisplayable()) {
            quanLyNhanVien_jPanel.setVisible(false);
        }
        if (quanLyKho_jPanel.isDisplayable()) {
            quanLyKho_jPanel.setVisible(false);
        }
        quanLyThucDon_jPanel.setVisible(true);
        add(quanLyThucDon_jPanel, BorderLayout.CENTER);
    }//GEN-LAST:event_thucDon_jButtonActionPerformed

    private void themMonAn_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themMonAn_jButtonActionPerformed
        // TODO add your handling code here:
        themMonAn_jDialog.pack();
        themMonAn_jDialog.setLocationRelativeTo(null);
        themMonAn_jDialog.setVisible(true);
    }//GEN-LAST:event_themMonAn_jButtonActionPerformed

    private void searchMonAn_jTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchMonAn_jTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMonAn_jTextFieldFocusGained

    private void searchMonAn_jTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchMonAn_jTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMonAn_jTextFieldFocusLost

    private void searchMonAn_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMonAn_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMonAn_jButton1ActionPerformed

    private void searchNhanVien_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNhanVien_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchNhanVien_jTextFieldActionPerformed

    private void searchMonAn_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMonAn_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMonAn_jTextFieldActionPerformed

    private void suaAnhMonAnTuFile_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaAnhMonAnTuFile_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suaAnhMonAnTuFile_jButtonActionPerformed

    private void suaTenMonAn_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaTenMonAn_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suaTenMonAn_jTextFieldActionPerformed

    private void confirm_SuaMonAn_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_SuaMonAn_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm_SuaMonAn_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        themMonAn_jDialog.setVisible(false);
        themTenMonAn_jTextField.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void confirmThemMonAn_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmThemMonAn_jButtonActionPerformed
        // TODO add your handling code here:
        themMonAn_jDialog.setVisible(false);
        themTenMonAn_jTextField.setText("");
        confirmThemMonAn_jOptionPane.showMessageDialog(quanLyThucDon_jPanel, "Them mon an thanh cong!");
    }//GEN-LAST:event_confirmThemMonAn_jButtonActionPerformed

    private void themTenMonAn_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themTenMonAn_jTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_themTenMonAn_jTextFieldActionPerformed

    private void themAnhMonAnTuFile_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themAnhMonAnTuFile_jButtonActionPerformed
        // TODO add your handling code here:
        String tenMon = themTenMonAn_jTextField.getText();
        themMonAn_jFileChooser.showOpenDialog(null);
        File anhMonAn = themMonAn_jFileChooser.getSelectedFile();
        String link_image = anhMonAn.getAbsolutePath();
    }//GEN-LAST:event_themAnhMonAnTuFile_jButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_themNV_jButton;
    private javax.swing.JButton cancle_XoaSuaMonAn_jButton;
    private javax.swing.JLabel cccd_jLabel;
    private javax.swing.JTextField cccd_jTextField;
    private javax.swing.JLabel chucVu_jLabel;
    private javax.swing.JTextField chucVu_jTextField;
    private javax.swing.JButton confirmThemMonAn_jButton;
    private javax.swing.JOptionPane confirmThemMonAn_jOptionPane;
    private javax.swing.JButton confirm_SuaMonAn_jButton1;
    private javax.swing.JButton confirm_ThemNV_Button;
    private javax.swing.JOptionPane confirm_themNV_jOptionPane;
    private javax.swing.JLabel diaChi_jLabel;
    private javax.swing.JTextField diaChi_jTextField;
    private javax.swing.JLabel eMail_jLabel;
    private javax.swing.JTextField email_JTextField;
    private javax.swing.JComboBox<String> gioiTinh_JComboBox;
    private javax.swing.JLabel gioi_Tinh_jLabel;
    private javax.swing.JLabel hoTen__jLabel;
    private javax.swing.JTextField hoTen_jTextField;
    private javax.swing.JButton hoaDon_jButton;
    private javax.swing.JLabel idNhanVien_jLabel;
    private javax.swing.JTextField idNhanVien_jTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton khachHang_jButton;
    private javax.swing.JButton kho_jButton;
    private javax.swing.JLabel luong_jLabel;
    private javax.swing.JTextField luong_jTextField;
    private com.raven.datechooser.DateChooser ngaySinh_dateChooser;
    private javax.swing.JLabel ngaySinh_jLabel;
    private javax.swing.JTextField ngaySinh_jTextField;
    private com.raven.datechooser.DateChooser ngayVaoLam_dateChooser;
    private javax.swing.JLabel ngayVaoLam_jLabel;
    private javax.swing.JTextField ngayVaoLam_jTextField;
    private javax.swing.JButton nhanVien_jButton;
    private javax.swing.JPanel quanLyHoaDon_jPanel;
    private javax.swing.JPanel quanLyKhachHang_jPanel;
    private javax.swing.JPanel quanLyKho_jPanel;
    private javax.swing.JPanel quanLyNhanVien_jPanel;
    private javax.swing.JPanel quanLyThucDon_jPanel;
    private javax.swing.JComboBox<String> searchMonAnTheo_jComboBox;
    private javax.swing.JButton searchMonAn_jButton1;
    private javax.swing.JPanel searchMonAn_jPanel;
    private javax.swing.JTextField searchMonAn_jTextField;
    private javax.swing.JComboBox<String> searchNhanVienTheo_jComboBox;
    private javax.swing.JButton searchNhanVien_jButton;
    private javax.swing.JPanel searchNhanVien_jPanel;
    private javax.swing.JTextField searchNhanVien_jTextField;
    private javax.swing.JTable showNhanVien_jTable;
    private javax.swing.JFormattedTextField soDienThoai_jFormattedTextField;
    private javax.swing.JLabel soDienThoai_jLabel;
    private javax.swing.JButton suaAnhMonAnTuFile_jButton;
    private javax.swing.JLabel suaAnhMonAn_jLabel1;
    private javax.swing.JTextField suaLoaiMonAn_jTextField;
    private javax.swing.JLabel suaTenMonAn_jLabel;
    private javax.swing.JTextField suaTenMonAn_jTextField;
    private keeptoo.KGradientPanel thanhBen_JPanel;
    private javax.swing.JButton themAnhMonAnTuFile_jButton;
    private javax.swing.JLabel themAnhMonAn_jLabel;
    private javax.swing.JLabel themLoaiMonAn_jLabel;
    private javax.swing.JLabel themLoaiMonAn_jLabel1;
    private javax.swing.JTextField themLoaiMonAn_jTextField;
    private javax.swing.JButton themMonAn_jButton;
    private javax.swing.JDialog themMonAn_jDialog;
    private javax.swing.JFileChooser themMonAn_jFileChooser;
    private javax.swing.JButton themNV_jButton;
    private javax.swing.JDialog themNV_jDialog;
    private javax.swing.JTextField themTenMonAn_jTextField;
    private javax.swing.JLabel themTenMon_jLabel;
    private javax.swing.JButton thucDon_jButton;
    private javax.swing.JButton xoaMonAn_jButton;
    public static javax.swing.JDialog xoa_suaMonAn_jDialog;
    // End of variables declaration//GEN-END:variables
}
